#!/bin/sh
# prerm script for nemo-hide
#
# see: dh_installdeb(1)

set -e

case "$1" in
    remove|upgrade|deconfigure)
        rm -f /var/lib/update-notifier/user.d/nemo-hide-notification
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules -c  nemo-hide.private
fi
# End automatically added section


exit 0
